spring:
  application:
    name: infinite_scroll
  datasource:
    url: jdbc:mariadb://localhost:3306/local_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true